### PR TITLE
Fix(refiner): Atomically update last block file

### LINKED ISSUE #33: Block number file is empty after hard restart
Sometimes after the node had restarted/hard restarted file .REFINER_LAST_BLOCK becomes empty and that leads to an error on the refiner start.

Example of an error (sorry for image :) ):
image

### PR DESCRIPTION
**Pull request by birchmd**
Fixes #33 

This PR changes the logic for saving the last processed block height to a file so that it writes to a new file and then moves onto the main file. This ensures the main file is atomically updated (there is never a state where the file is cleared, but not yet written to).

### CODE REVIEW

File: refiner-app/src/store.rs [hunk 1]
```diff
@@ -99,16 +99,21 @@ async fn save_last_block_height<P: AsRef<std::path::Path>>(storage_path: P, bloc
...
 
-    let file = tokio::fs::File::create(path).await.unwrap();
+    // Write the data to a height-specific file to avoid clearing the main file
+    let temp_path = path.join(format!(".{block_height}"));
+    let temp_file = tokio::fs::File::create(&temp_path).await.unwrap();
 
     {
-        let mut writer = tokio::io::BufWriter::new(file);
+        let mut writer = tokio::io::BufWriter::new(temp_file);
         let data = serde_json::to_string(&block_height).unwrap();
```
Comment (aleksuss) [inline refiner-app/src/store.rs:110]: It seems that serde usage here is overkill 😄 
```suggestion
        writer.write_all(data.to_string().as_bytes()).await.unwrap();
```

**Review by aleksuss — DISMISSED** [review]
Overall looks good, with tiny nitpicks

**Review by SozinM — APPROVED** [review]

File: refiner-app/src/store.rs (hunk 1 above)
Comment (aleksuss) [reply refiner-app/src/store.rs:110]:
```rust
async fn save_last_block_height<P: AsRef<std::path::Path>>(storage_path: P, block_height: u64) {
    let path = storage_path.as_ref();
    if !path.exists() {
        tokio::fs::create_dir_all(path).await.unwrap();
    }
    let file_path = path.join(STORE_INFO_FILE);

    tokio::fs::write(file_path, block_height.to_string())
        .await
        .unwrap();
    tracing::trace!("Last block height {} saved.", block_height);
}
```
Shorter version.

Comment (birchmd) [reply refiner-app/src/store.rs:110]: I don't think it works atomically to simply call `tokio::fs::write`. It could still be possible for an unexpected shutdown to leave `STORE_INFO_FILE` in a corrupted (empty) state. The point of writing to another file and then using `rename` is that the initial write does not change `STORE_INFO_FILE`, so an interrupt at that point leaves the file in tact. And `rename` itself is safe because it uses OS functions under the hood which are atomic, regardless of what happens to the running application.

I agree the serde call is not needed though.

Comment (aleksuss) [reply refiner-app/src/store.rs:110]: And trivial test could be added:
```rust
#[tokio::test]
async fn test_save_last_block_height() {
    let tmp_dir = std::env::temp_dir();
    save_last_block_height(&tmp_dir, 11111).await;
    let block_height = load_last_block_height(tmp_dir).await;

    assert_eq!(block_height, Some(11111))
}
```

Comment (birchmd) [reply refiner-app/src/store.rs]: Good call. Done in https://github.com/aurora-is-near/borealis-engine-lib/pull/34/commits/d9d83d4bae498ebbf1b454df4207e30e2c20517b

**Review by aleksuss — APPROVED** [review]
